/**
 * @file src/security/securityConstants.js
 * @description Standardized event types and resource classifications for the Enterprise Authorization Framework.
 */

export const SecurityEventTypes = {
  AUTHORIZATION_ALLOWED: 'AUTHORIZATION_ALLOWED',
  AUTHORIZATION_DENIED: 'AUTHORIZATION_DENIED',
  OWNERSHIP_DENIED: 'OWNERSHIP_DENIED',
  FIELD_ACCESS_DENIED: 'FIELD_ACCESS_DENIED',
  QUERY_SANITIZED: 'QUERY_SANITIZED',
  AGGREGATION_BLOCKED: 'AGGREGATION_BLOCKED',
  ROLE_ESCALATION_ATTEMPT: 'ROLE_ESCALATION_ATTEMPT',
  CROSS_BRANCH_ACCESS: 'CROSS_BRANCH_ACCESS',
  CROSS_DEPARTMENT_ACCESS: 'CROSS_DEPARTMENT_ACCESS',
  EXPORT_DENIED: 'EXPORT_DENIED',
  IMPORT_DENIED: 'IMPORT_DENIED',
  SECURITY_EXCEPTION: 'SECURITY_EXCEPTION'
};

export const ResourceClassifications = {
  PUBLIC: 'PUBLIC',
  INTERNAL: 'INTERNAL',
  CONFIDENTIAL: 'CONFIDENTIAL',
  HIGHLY_CONFIDENTIAL: 'HIGHLY_CONFIDENTIAL',
  PRIVATE: 'PRIVATE'
};

export default {
  SecurityEventTypes,
  ResourceClassifications
};
